// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// init_log_table
void init_log_table();
RcppExport SEXP _HrdDetective_init_log_table() {
BEGIN_RCPP
    init_log_table();
    return R_NilValue;
END_RCPP
}
// baf_bayes_fit_cpp
List baf_bayes_fit_cpp(NumericVector ratio, NumericVector bf, NumericVector seg, StringVector zygosity, NumericVector n_exp, NumericVector m_exp, NumericVector baf_exp, NumericVector ratio_exp, NumericVector trunca_ratio_t, NumericVector trunca_baf_t, NumericVector potential_pos, NumericVector beta, NumericVector ratio_sd, NumericVector bf_sd, NumericVector t_bf_sd_logit);
RcppExport SEXP _HrdDetective_baf_bayes_fit_cpp(SEXP ratioSEXP, SEXP bfSEXP, SEXP segSEXP, SEXP zygositySEXP, SEXP n_expSEXP, SEXP m_expSEXP, SEXP baf_expSEXP, SEXP ratio_expSEXP, SEXP trunca_ratio_tSEXP, SEXP trunca_baf_tSEXP, SEXP potential_posSEXP, SEXP betaSEXP, SEXP ratio_sdSEXP, SEXP bf_sdSEXP, SEXP t_bf_sd_logitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericVector >::type ratio(ratioSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bf(bfSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type seg(segSEXP);
    Rcpp::traits::input_parameter< StringVector >::type zygosity(zygositySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type n_exp(n_expSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type m_exp(m_expSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type baf_exp(baf_expSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ratio_exp(ratio_expSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type trunca_ratio_t(trunca_ratio_tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type trunca_baf_t(trunca_baf_tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type potential_pos(potential_posSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ratio_sd(ratio_sdSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bf_sd(bf_sdSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t_bf_sd_logit(t_bf_sd_logitSEXP);
    rcpp_result_gen = Rcpp::wrap(baf_bayes_fit_cpp(ratio, bf, seg, zygosity, n_exp, m_exp, baf_exp, ratio_exp, trunca_ratio_t, trunca_baf_t, potential_pos, beta, ratio_sd, bf_sd, t_bf_sd_logit));
    return rcpp_result_gen;
END_RCPP
}
// baf_bayes_one_fit_cpp
NumericVector baf_bayes_one_fit_cpp(NumericVector ratio, NumericVector bf, StringVector zygosity, NumericVector n_v, NumericVector m_v, NumericVector ratio_v, NumericVector baf_v, NumericVector trunca_ratio_t_v, NumericVector trunca_baf_t_v, NumericVector ratio_sd, NumericVector bf_sd, NumericVector bf_sd_logit);
RcppExport SEXP _HrdDetective_baf_bayes_one_fit_cpp(SEXP ratioSEXP, SEXP bfSEXP, SEXP zygositySEXP, SEXP n_vSEXP, SEXP m_vSEXP, SEXP ratio_vSEXP, SEXP baf_vSEXP, SEXP trunca_ratio_t_vSEXP, SEXP trunca_baf_t_vSEXP, SEXP ratio_sdSEXP, SEXP bf_sdSEXP, SEXP bf_sd_logitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type ratio(ratioSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bf(bfSEXP);
    Rcpp::traits::input_parameter< StringVector >::type zygosity(zygositySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type n_v(n_vSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type m_v(m_vSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ratio_v(ratio_vSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type baf_v(baf_vSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type trunca_ratio_t_v(trunca_ratio_t_vSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type trunca_baf_t_v(trunca_baf_t_vSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ratio_sd(ratio_sdSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bf_sd(bf_sdSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bf_sd_logit(bf_sd_logitSEXP);
    rcpp_result_gen = Rcpp::wrap(baf_bayes_one_fit_cpp(ratio, bf, zygosity, n_v, m_v, ratio_v, baf_v, trunca_ratio_t_v, trunca_baf_t_v, ratio_sd, bf_sd, bf_sd_logit));
    return rcpp_result_gen;
END_RCPP
}
// pileup_manual_vectors
List pileup_manual_vectors(CharacterVector seqnames, IntegerVector positions, CharacterVector cigars, CharacterVector sequences, CharacterVector qualities, IntegerVector mapqs, IntegerVector flags, IntegerVector qwidths, std::string seqname, int start, int end, int min_mapq, int min_base_quality, int min_depth, float min_af, int max_depth, bool distinguish_strands, bool distinguish_nucleotides, bool ignore_query_Ns, bool include_deletions, bool include_insertions);
RcppExport SEXP _HrdDetective_pileup_manual_vectors(SEXP seqnamesSEXP, SEXP positionsSEXP, SEXP cigarsSEXP, SEXP sequencesSEXP, SEXP qualitiesSEXP, SEXP mapqsSEXP, SEXP flagsSEXP, SEXP qwidthsSEXP, SEXP seqnameSEXP, SEXP startSEXP, SEXP endSEXP, SEXP min_mapqSEXP, SEXP min_base_qualitySEXP, SEXP min_depthSEXP, SEXP min_afSEXP, SEXP max_depthSEXP, SEXP distinguish_strandsSEXP, SEXP distinguish_nucleotidesSEXP, SEXP ignore_query_NsSEXP, SEXP include_deletionsSEXP, SEXP include_insertionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type seqnames(seqnamesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type positions(positionsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type cigars(cigarsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type sequences(sequencesSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type qualities(qualitiesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type mapqs(mapqsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type flags(flagsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type qwidths(qwidthsSEXP);
    Rcpp::traits::input_parameter< std::string >::type seqname(seqnameSEXP);
    Rcpp::traits::input_parameter< int >::type start(startSEXP);
    Rcpp::traits::input_parameter< int >::type end(endSEXP);
    Rcpp::traits::input_parameter< int >::type min_mapq(min_mapqSEXP);
    Rcpp::traits::input_parameter< int >::type min_base_quality(min_base_qualitySEXP);
    Rcpp::traits::input_parameter< int >::type min_depth(min_depthSEXP);
    Rcpp::traits::input_parameter< float >::type min_af(min_afSEXP);
    Rcpp::traits::input_parameter< int >::type max_depth(max_depthSEXP);
    Rcpp::traits::input_parameter< bool >::type distinguish_strands(distinguish_strandsSEXP);
    Rcpp::traits::input_parameter< bool >::type distinguish_nucleotides(distinguish_nucleotidesSEXP);
    Rcpp::traits::input_parameter< bool >::type ignore_query_Ns(ignore_query_NsSEXP);
    Rcpp::traits::input_parameter< bool >::type include_deletions(include_deletionsSEXP);
    Rcpp::traits::input_parameter< bool >::type include_insertions(include_insertionsSEXP);
    rcpp_result_gen = Rcpp::wrap(pileup_manual_vectors(seqnames, positions, cigars, sequences, qualities, mapqs, flags, qwidths, seqname, start, end, min_mapq, min_base_quality, min_depth, min_af, max_depth, distinguish_strands, distinguish_nucleotides, ignore_query_Ns, include_deletions, include_insertions));
    return rcpp_result_gen;
END_RCPP
}
// pileup_manual
DataFrame pileup_manual(std::string bam_file, std::string seqname, int start, int end, int min_mapq, float min_af, int min_base_quality, int min_depth, int max_depth, bool distinguish_strands, bool distinguish_nucleotides, bool ignore_query_Ns, bool include_deletions, bool include_insertions);
RcppExport SEXP _HrdDetective_pileup_manual(SEXP bam_fileSEXP, SEXP seqnameSEXP, SEXP startSEXP, SEXP endSEXP, SEXP min_mapqSEXP, SEXP min_afSEXP, SEXP min_base_qualitySEXP, SEXP min_depthSEXP, SEXP max_depthSEXP, SEXP distinguish_strandsSEXP, SEXP distinguish_nucleotidesSEXP, SEXP ignore_query_NsSEXP, SEXP include_deletionsSEXP, SEXP include_insertionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type bam_file(bam_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type seqname(seqnameSEXP);
    Rcpp::traits::input_parameter< int >::type start(startSEXP);
    Rcpp::traits::input_parameter< int >::type end(endSEXP);
    Rcpp::traits::input_parameter< int >::type min_mapq(min_mapqSEXP);
    Rcpp::traits::input_parameter< float >::type min_af(min_afSEXP);
    Rcpp::traits::input_parameter< int >::type min_base_quality(min_base_qualitySEXP);
    Rcpp::traits::input_parameter< int >::type min_depth(min_depthSEXP);
    Rcpp::traits::input_parameter< int >::type max_depth(max_depthSEXP);
    Rcpp::traits::input_parameter< bool >::type distinguish_strands(distinguish_strandsSEXP);
    Rcpp::traits::input_parameter< bool >::type distinguish_nucleotides(distinguish_nucleotidesSEXP);
    Rcpp::traits::input_parameter< bool >::type ignore_query_Ns(ignore_query_NsSEXP);
    Rcpp::traits::input_parameter< bool >::type include_deletions(include_deletionsSEXP);
    Rcpp::traits::input_parameter< bool >::type include_insertions(include_insertionsSEXP);
    rcpp_result_gen = Rcpp::wrap(pileup_manual(bam_file, seqname, start, end, min_mapq, min_af, min_base_quality, min_depth, max_depth, distinguish_strands, distinguish_nucleotides, ignore_query_Ns, include_deletions, include_insertions));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_HrdDetective_init_log_table", (DL_FUNC) &_HrdDetective_init_log_table, 0},
    {"_HrdDetective_baf_bayes_fit_cpp", (DL_FUNC) &_HrdDetective_baf_bayes_fit_cpp, 15},
    {"_HrdDetective_baf_bayes_one_fit_cpp", (DL_FUNC) &_HrdDetective_baf_bayes_one_fit_cpp, 12},
    {"_HrdDetective_pileup_manual_vectors", (DL_FUNC) &_HrdDetective_pileup_manual_vectors, 21},
    {"_HrdDetective_pileup_manual", (DL_FUNC) &_HrdDetective_pileup_manual, 14},
    {NULL, NULL, 0}
};

RcppExport void R_init_HrdDetective(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
