# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

init_log_table <- function() {
    invisible(.Call(`_HrdDetective_init_log_table`))
}

baf_bayes_fit_cpp <- function(ratio, bf, seg, zygosity, n_exp, m_exp, baf_exp, ratio_exp, trunca_ratio_t, trunca_baf_t, potential_pos, beta, ratio_sd, bf_sd, t_bf_sd_logit) {
    .Call(`_HrdDetective_baf_bayes_fit_cpp`, ratio, bf, seg, zygosity, n_exp, m_exp, baf_exp, ratio_exp, trunca_ratio_t, trunca_baf_t, potential_pos, beta, ratio_sd, bf_sd, t_bf_sd_logit)
}

baf_bayes_one_fit_cpp <- function(ratio, bf, zygosity, n_v, m_v, ratio_v, baf_v, trunca_ratio_t_v, trunca_baf_t_v, ratio_sd, bf_sd, bf_sd_logit) {
    .Call(`_HrdDetective_baf_bayes_one_fit_cpp`, ratio, bf, zygosity, n_v, m_v, ratio_v, baf_v, trunca_ratio_t_v, trunca_baf_t_v, ratio_sd, bf_sd, bf_sd_logit)
}

pileup_manual_vectors <- function(seqnames, positions, cigars, sequences, qualities, mapqs, flags, qwidths, seqname, start, end, min_mapq = 0L, min_base_quality = 0L, min_depth = 0L, min_af = 0.2, max_depth = 1000000L, distinguish_strands = FALSE, distinguish_nucleotides = TRUE, ignore_query_Ns = TRUE, include_deletions = FALSE, include_insertions = FALSE) {
    .Call(`_HrdDetective_pileup_manual_vectors`, seqnames, positions, cigars, sequences, qualities, mapqs, flags, qwidths, seqname, start, end, min_mapq, min_base_quality, min_depth, min_af, max_depth, distinguish_strands, distinguish_nucleotides, ignore_query_Ns, include_deletions, include_insertions)
}

pileup_manual <- function(bam_file, seqname, start, end, min_mapq = 0L, min_af = 0.2, min_base_quality = 0L, min_depth = 0L, max_depth = 1000000L, distinguish_strands = FALSE, distinguish_nucleotides = TRUE, ignore_query_Ns = TRUE, include_deletions = FALSE, include_insertions = FALSE) {
    .Call(`_HrdDetective_pileup_manual`, bam_file, seqname, start, end, min_mapq, min_af, min_base_quality, min_depth, max_depth, distinguish_strands, distinguish_nucleotides, ignore_query_Ns, include_deletions, include_insertions)
}

